<?php 
if (isset($this)){
	$THISPAGE = array_key_exists('thispage', $this->vars)? $this->thispage : 'xxx-xxx';
} else{
	$THISPAGE = isset($THISPAGE) ? $THISPAGE: 'xxx-xxx';
}
$_pages = Array(
	"apps" => Array(
		"title" => "Applications", 
		"subs" => Array(
			"map" => Array("title" => "Map Application", "url" => "/map/")
		),
	),
	
	"docs" => Array(
		"title" => "Documentation", 
		"subs" => Array(
			"climate" => Array("title" => "Climate Files", "url" => "/docs/climate.phtml")
		),
	),
);
?>
<div class="container" id="iem-header">
<div class="navbar navbar-inverse">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/" style="padding:15px"><span style="font-size: 1.5em;">Daily Erosion Project</span></a>
	</div>
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
        
<li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" 
	href="#"> <span class="glyphicon glyphicon-home"></span> </a>
	<ul class="dropdown-menu">
		<li><a href="/">Iowa Environmental Mesonet</a></li>
		<li><a href="http://idep.agron.iastate.edu">Daily Erosion Project</a></li>
	</ul></li>
        
<?php 
$ar = preg_split('/-/', $THISPAGE);
function get_title($page){
	if (array_key_exists("icon", $page)){
		return sprintf("<div class=\"hidden-sm\">%s<b class=\"caret\"></b></div>"
				."<span class=\"glyphicon glyphicon-%s visible-sm\"></span>",
			$page["title"], $page["icon"] );
	}
	return sprintf("%s<span class=\"caret\"></span>", $page["title"]);
}

while( list($idx, $page) = each($_pages) )
{
  	echo sprintf("<li class=\"dropdown%s\">\n<a class=\"dropdown-toggle\" 
		data-toggle=\"dropdown\" href=\"#\">%s</a>\n", 
      ($ar[0] == $idx) ? " active" : "", get_title($page));

    echo "<ul class=\"dropdown-menu\">\n";
    while( list($idx2, $page2) = each($page["subs"]) )
    {
       echo sprintf("<li><a%s href=\"%s\">%s</a></li>\n", 
         ($ar[1] == $idx2 && $ar[0] == $idx) ? " class=\"active\"" : "",
           $page2["url"],  $page2["title"] );
    }
    echo "</ul>\n</li>\n";
}

/* Look for related IEM Apps */
if (defined('IEM_APPID')){
	include_once(dirname(__FILE__)."/../database.inc.php");
	$_mesosite = iemdb("mesosite");
	pg_prepare($_mesosite, "_SELECTOR_", "SELECT * from iemapps where appid in
		(SELECT appid from iemapps_tags WHERE tag in (SELECT tag from iemapps_tags where appid = $1)
		and appid != $1) ORDER by name ASC");
	$_rs = pg_execute($_mesosite, "_SELECTOR_", Array(IEM_APPID));
	if (pg_numrows($_rs) > 0){
		echo "<li class=\"dropdown\"><a class=\"dropdown-trigger\" data-toggle=\"dropdown\" href=\"#\"><div class=\"hidden-sm\">Related<b class=\"caret\"></b></div>"
				."<span class=\"glyphicon glyphicon-plus visible-sm\"></span></a>\n";
		echo "<ul class=\"dropdown-menu\">\n";
		for ($i=0;$_row=@pg_fetch_assoc($_rs,$i);$i++){
			$url =  $_row["url"];
			if (substr($_row["url"],0,1) == "h"){
				$url = $_row["url"];
			}
			echo sprintf("<li><a href=\"%s\">%s</a></li>",
					$url,  $_row["name"] );
		}
		echo "</ul></li>\n";
	}
	pg_close($_mesosite);
}

  ?>
</ul>
        </div>
      </div>
    </div>
