<?php 
require '../../config/settings.inc.php';
require_once '../../include/myview.php';

$t = new MyView();
$t->title = "Climate File Documentation";
$t->content = <<<EOF
<ol class="breadcrumb">
		<li><a href="/">IDEP Homepage</a></li>
		<li class="active">Climate File Documentation</li>
</ol>

<h3>Climate File Documentation</h3>

<h4>Precipitation</h4>

<p>Of course, precipitation is vital to erosion modeling.  One of the unique
		aspects of our project is how we use high resolution depictions of 
		precipitation to drive our estimates.  One of the major updates included
		with IDEPv2 was the change from using NCEP stage IV precipitation estimates
		to NCEP MRMS estimates.  Here is an example:</p>
		
<div class="row">
	<div class="col-md-6">
    <img src="/images/stage4_example.png" alt="Stage IV Example"
		class="img img-responsive"/>
	</div>
	<div class="col-md-6">
    <img src="/images/mrms_example.png" alt="Stage IV Example"
		class="img img-responsive"/>
	</div>
		
</div>
    	
<h4>Solar Radiation</h4>

<p>The amount of energy received by the Earth's surface from the sun is the
important driver of plant growth.  The WEPP model contains a crop growth model
that is sensitive to daily solar radiation data.  For IDEPv2, this information
is provided on a 0.01 degree grid based on a nearest neighbor analysis of 
<a href="http://mesonet.agron.iastate.edu/agclimate/">Iowa State Soil Moisture Network</a>
data.  This routine does not produce fine scale detail as there are only 20 
some observations in the state. In the future, the hope is to use high resolution
numerical modelling analysis to provide fine scale detail.</p>

<p>The realtime runs are started at 12:30 AM each day.  On some days, for
various reasons, the solar radiation summary data is not yet available at this 
time.  When this situation happens, the climate file generation script uses the
previous day's data as today's data.  A process later in the day attempts to 
correct this estimate as the actual data comes in.  Having missing solar 
radiation data at 12:30 AM is not considered a show stopping issue and the
previous day's estimates are "good enough".</p>

<h4>Temperature</h4>

<p>WEPP requires the daily high and low temperature.  In general and with
Iowa's flat terrain, these values are very smooth over the state.  An 
approximate 24 km analysis of <a href="http://mesonet.agron.iastate.edu/">Iowa Mesonet</a>
		observations provides these variables to WEPP.</p>

EOF;

$t->render('single.phtml');
?>
