<?php 
require '../../config/settings.inc.php';
require_once '../../include/myview.php';

$t = new MyView();
$t->title = "Climate File Documentation";
$t->content = <<<EOF
<ol class="breadcrumb">
		<li><a href="/">IDEP Homepage</a></li>
		<li><a href="/docs/">Documentation</a></li>
		<li class="active">Climate Files</li>
</ol>

<h3>Climate File Documentation</h3>

<a href="#bpsense">Breakpoint Sensitivity Test</a>
		
<h4>Dew Point</h4>
		
<p>WEPP climate files want daily averaged dew point.  This value is provided
		by the <a href="http://mesonet.agron.iastate.edu/iemre/">IEM Daily ReAnalysis</a>
		. It is derived by a gridded analysis of surface observation data.</p>
		
<h4>Precipitation</h4>

<p>Of course, precipitation is vital to erosion modeling.  One of the unique
		aspects of our project is how we use high resolution depictions of 
		precipitation to drive our estimates.  One of the major updates included
		with IDEPv2 was the change from using NCEP stage IV precipitation estimates
		to NCEP MRMS estimates.  Here is an example:</p>
		
<div class="row">
	<div class="col-md-6">
    <img src="/images/stage4_example.png" alt="Stage IV Example"
		class="img img-responsive"/>
	</div>
	<div class="col-md-6">
    <img src="/images/mrms_example.png" alt="Stage IV Example"
		class="img img-responsive"/>
	</div>
		
</div>
    	
<p>The MRMS product provides intensity estimates on a 2 minute timestep.  The
prospect of directly including these 2 minute interval data within the WEPP
climate file would inflate the filesize and runtime.  So an algorithm is used
to collapse down the 2 minute interval data into periods that mostly
retain the largest rates.  This algorithm writes breakpoints whenever
the instantaneous 2 minute accumulatio is over 1 mm and/or the accumulated
precipitation since the last breakpoint is 2 mm.
The result is a WEPP climate file with fewer break
points, but still have the peak intensities captured.  Any day without at
least 0.254 mm accumulation is set to zero.  If the day accumulation was less than
2 mm, the breakpoints used are simply the start and end timestamp of the
precipitation event.</p>
		
<h4>Solar Radiation</h4>

<p>The amount of energy received by the Earth's surface from the sun is the
important driver of plant growth.  The WEPP model contains a crop growth model
that is sensitive to daily solar radiation data.  For IDEPv2, this information
is provided on a 0.01 degree grid based on a nearest neighbor analysis of 
<a href="http://mesonet.agron.iastate.edu/agclimate/">Iowa State Soil Moisture Network</a>
data.  This routine does not produce fine scale detail as there are only 20 
some observations in the state. In the future, the hope is to use high resolution
numerical modelling analysis to provide fine scale detail.</p>

<p>The realtime runs are started at 12:30 AM each day.  On some days, for
various reasons, the solar radiation summary data is not yet available at this 
time.  When this situation happens, the climate file generation script uses the
previous day's data as today's data.  A process later in the day attempts to 
correct this estimate as the actual data comes in.  Having missing solar 
radiation data at 12:30 AM is not considered a show stopping issue and the
previous day's estimates are "good enough".</p>

<h4>Temperature</h4>

<p>WEPP requires the daily high and low temperature.  In general and with
Iowa's flat terrain, these values are very smooth over the state.  An 
approximate 24 km analysis of <a href="http://mesonet.agron.iastate.edu/">Iowa Mesonet</a>
observations provides these variables to WEPP.</p>

<h4>Wind</h4>
		
	<p>WEPP wants the daily average wind speed and direction.  For our purposes,
		the wind direction is unused so is always set to north (0 degrees). The
		averaged wind speed is provided by the
		<a href="http://mesonet.agron.iastate.edu/iemre/">IEM Daily ReAnalysis</a>.</p>

<a name="bpsense"></a>
<h4>Sensitivity Test to Changing Breakpoint Calculation</h4>

		<p>The initial choice of a 10 mm precipitation accumulation prior to
		writing a breakpoint file was a bit arbitrary.  A sensitivity test was
		done to investigate two options available for the breakpoint calculation
		code:<br />
		<ul>
		 <li>Accumulation Threshold</li>
		 <li>Intensity Threshold</li>
		</ul></p>
		
		<p>These two parameters were varied from 1 to 20 mm, with each combination
		producing a WEPP run for comparison.  This comparison was made for
		11 June 2015 at longitude 94.86W and 40.84N.  Each plot shown below
		is normalized to the maximum value found in the plot.  This allows
		for simple relative comparison to the amount of change that existed
		with the parameter change.</p>
		
		<p>This figure displays the number of breakpoints computed.</p>
		<img src="/images/points_experiment.png" class="img img-responsive">

		<p>This figure displays the WEPP computed amount of soil displacement.</p>
		<img src="/images/loss_experiment.png" class="img img-responsive">
		
		<p>This figure displays the resulting largest precipitation rate
		based on the break points generated.</p>
		<img src="/images/maxrate_experiment.png" class="img img-responsive">
		
		<p>This figure displays the WEPP computed delivery.</p>
		<img src="/images/delivery_experiment.png" class="img img-responsive">
		
		<p>This figure displays the WEPP computed runoff.  Interestingly, it
		appears that runoff is not sensitive to the intensities found in
		the climate file.</p>
		<img src="/images/runoff_experiment.png" class="img img-responsive">
		
EOF;

$t->render('single.phtml');
?>
