<?php 
require '../../config/settings.inc.php';
require_once '../../include/myview.php';

$t = new MyView();
$t->title = "Daily Erosion Documentation";
$t->thispage = "docs-main";
$t->content = <<<EOF
<ol class="breadcrumb">
		<li><a href="/">IDEP Homepage</a></li>
		<li class="active">Documentation</li>
</ol>

<h2>Daily Erosion Project (DEP) Documentation</h2>

<p>The four major DEP components are the soil erosion model (WEPP); the soil,
		topography, and land management input database; daily weather information;
		and a sampling and scaling approach for the daily modeling and reporting, 
		respectively, of hillslope soil erosion and water runoff in Iowa. 
		Substantial revisions from the first version (Cruse et al. 2006) 
		include complex (versus uniform) hillslope modeling, annually updated 
		remotely sensed soil management and land use databases 
		(rather than NRI-supplied information), and hydrological 
		(rather than geopolitical) discretization of the state for analysis 
		and reporting.  Outputs reported for each HUC 12 include average daily precipitation, average soil detachment per hillslope and average delivery of detached sediment to the base of the modeled hillslope.
		
<p>Water Erosion Prediction Project. The Water Erosion Prediction Project (WEPP) 
		hillslope model (Flanagan and Nearing 1995) was selected for the DEP. 
		WEPP simulates rill and interrill erosion by rainfall and runoff and 
		spatiotemporal distributions of soil detachment and sediment delivery 
		(Flanagan and Nearing 1995). The basic element on which WEPP is implemented 
		is a hillslope, which consists of one or more overland flow elements (OFEs). 
		An OFE is a hillslope segment that represents a unique combination of slope, 
		soil type, and land use.
	
<p>Studies have validated the accuracy and unbiasedness of WEPP erosion estimates 
		and confirmed its applicability in a broad range of conditions 
		(Tiwari et al. 2000; Laflen et al. 2004). Motivations to select WEPP 
		for this project include its capability to run continuous daily simulations 
		and for modeling runoff and erosion on complex hillslopes. The DEP executes 
		WEPP as a continuous simulation model to generate daily estimates of runoff, 
		soil erosion, and soil moisture across Iowa. The WEPP model simulation is 
		supplied daily meteorological data, and the field specific crop and soil 
		management parameters needed to run the model are assembled in an annually 
		updated database.
	
<p>Input database. In addition to weather, the required WEPP inputs are topography, 
		soils, and agricultural land management. In the original implementation of 
		this project, slope, soil, and cropping and conservation practice information 
		were obtained from the NRI (Cruse et al. 2006). While the NRI sampling points 
		are based on actual locations (Nusser and Goebel 1997), the precise locations 
		cannot be disclosed due to privacy concerns and potential operator bias 
		(Cruse et al. 2006). Thus, in an effort to realistically assess soil erosion 
		on a spatially explicit and daily time scale, a new database of WEPP inputs 
		has been developed. The three primary biophysical conditions that are 
		inventoried for the DEP are topography, soils, and management.
	
<p>Assumed uniform slopes were the only topographic product available in the 
		first iteration of this project (Cruse et al. 2006). However, actual 
		hillslopes are typically complex. In terms of erosion modeling, complex 
		slopes can result in greatly different output relative to uniform slopes 
		because complex hillslopes often experience varying levels of erosion 
		and/or deposition at different points along the slope. For the DEP, 
		high-resolution topographic data are used to construct discrete hillslopes 
		for modeling erosion. Light Detection and Ranging (LiDAR) data, available 
		from the Iowa Department of Natural Resources, were processed with custom 
		algorithms to generate a 3 m (9.8 ft) digital elevation model (DEM) of 
		each HUC12 (USDA-NRCS, USGS, USEPA, 2012) watershed in Iowa. Details of 
		the hydrologic enforcement process can be found in Gelder (2015). 
		Processing settings maintain all depressions deeper than 9 cm 
		(0.5xRMSE) or larger than 100 square meters.
	
<p>Soil information is obtained from the gridded Soil Survey Geographic Database 
		(gSSURGO) (Soil Survey Staff, 2014). Geospatial soil data are registered 
		with the DEM for each HUC12 watershed.

<p>The final component of the WEPP input database is management, which is 
		separated into crop rotation (or sequences) and tillage practice for 
		each agricultural field in the state greater than 6 ha. Crop rotations 
		are determined for each field using the USDA-National Agricultural 
		Statistics Service (NASS) Cropland Data Layer (USDA, 2014). A six-year 
		rotation is derived from each field’s most recent crop history and is 
		used to preprocess the WEPP model to condition crop growth and antecedent 
		soil moisture conditions at model initiation. The land use for the model 
		(current) year within each field is based on the field’s six year rotation, 
		extending that rotation one additional year considering the preceding year’s crop. Land use data are updated annually (Tomer, 2015). Tillage practices are estimated for each field using Landsat 8 imagery. From the normalized difference tillage index (NDTI) the amount of residue cover on the soil surface is empirically derived (Gelder et al., 2009), which is then correlated to one of four tillage intensity classes which correspond to typical conventional tillage, intensive mulch tillage, reduced mulch tillage, and no-tillage practices. 

<p>After determination of crop rotation and tillage practice for each agricultural 
		land parcel, these parcels are rasterized along with the elevation and 
		soils data. This geo-referenced ensemble of topographic, soil, and land 
		management information is used to extract data to populate WEPP OFE and 
		hillslope input files.

<p><a href="climate.phtml">Meteorological Data</a></p>

<p>Sampling framework. Daily soil erosion and runoff are simulated for individual 
		hillslopes, but results are averaged across all modeled hillslopes within a 
		given HUC12 and reported at the HUC12 watershed level. Thus, a procedure 
		was developed to select hillslopes for soil erosion and water runoff 
		estimates and to transform the scale of the model output to that of the 
		HUC12 watershed. The primary goal of the sampling approach was to generate 
		statistically robust average runoff and erosion estimates for each HUC12 
		watershed in Iowa.
		
EOF;

$t->render('single.phtml');
?>