<?php 
require '../../config/settings.inc.php';
require_once '../../include/myview.php';

$t = new MyView();
$t->title = "Web Services";
$t->thispage = "docs-ws";
$t->content = <<<EOF
<ol class="breadcrumb">
		<li><a href="/">IDEP Homepage</a></li>
		<li><a href="/docs/">Documentation</a></li>
		<li class="active">Web Services</li>
</ol>

<h3>Daily Erosion Project Web Services</h3>

<p>The daily outputs of this project are made available on a per-HUC12 basis.
		There is a GeoJSON emitting web service that provides data to the
		<a href="/map/">map interface</a> found on this website.  You can use
		this service as well and here is the documentation for it:</p>

<p>The web server provides data on HTTPS-Only and sets the proper CORS header
		to allow cross site requests.</p>
<p>
<code>https://dailyerosion.org/geojson/huc12.py?</code>

		<br />HTTP GET options:<br />
		<ul>
			<li><code>date=YYYY-mm-dd</code>: specify a date to retrieve the
		results for.  <b>required</b></li>
		<li><code>domain=STATEABBR</code>: specify a two character state
		code to limit the results returned for.  For example, KS to return
		only those HUC12s within or touching Kansas. <b>optional</b>, defaults
		to return all HUC12s that DEP runs for.</li>
		<li><code>date2=YYYY-mm-dd</code>: when specified, the service returns
		aggregated data for the inclusive period between <code>date</code>
		and <code>date2</code>. <b>optional</b></li>
		<li><code>callback=myfunc</code>: this allows JSON-P style requests
		of the data. <b>optional</b></li>
		</ul>
		</p>
		
	<h4>Examples</h4>
		
		<p>Return all HUC12 results for 5 June 2016<br />
		<code>https://dailyerosion.org/geojson/huc12.py?date=2016-06-05</code>
	</p>

		<p>Return Minnesota HUC12 results for 5 June 2016<br />
		<code>https://dailyerosion.org/geojson/huc12.py?date=2016-06-05&amp;domain=MN</code>
	</p>
		
		<p>Return Kansas HUC12 totals for all of 2016<br />
		<code>https://dailyerosion.org/geojson/huc12.py?date=2016-01-01&amp;domain=KS&amp;date2=2016-12-31</code>
	</p>
		
EOF;

$t->render('single.phtml');
?>
