c     newly created parameter file for dailykr_byAnu_20200130
c     begin include file cchkr.inc

c     + + + COMMON BLOCK DESCRIPTION + + +
c     + + + INSERT DESCRIPTION HERE  + + +

      common/chkr/  dailykr(mxplan)

c     + + + VARIABLE DECLARATIONS + + +

      real  dailykr
 

c     + + + VARIABLE DEFINITIONS + + +

c     dailykr(mxplan) : store last adjusted Kr per channel when ch_run is set

c     end include file cchkr.inc