
c     begin include file cchvar.inc

c     + + + COMMON BLOCK DESCRIPTION + + +
c     + + + INSERT DESCRIPTION HERE  + + +

      common/chvar/  x(mxcseg),slope(mxcseg),chnlef,chnn(mxplan),
     1               chnks(mxplan),chntcr(mxplan),chnedm(mxplan),
     1               chneds(mxplan),chnk(mxplan),ch_run

c     + + + VARIABLE DECLARATIONS + + +

      real           x,slope,chnlef,chnn,chnks,chntcr,
     1               chnedm,chneds,chnk
      integer        ch_run

c     + + + VARIABLE DEFINITIONS + + +

c     x(mxcseg)      :
c     slope(mxcseg)  :
c     chnlef         :
c     chnn(mxplan)   :
c     chnks(mxplan)  :
c     chntcr(mxplan) :
c     chnedm(mxplan) :
c     chneds(mxplan) :
c     chnk(mxplan)   :
c     ch_run         : flag to indicate to use temporal channel erodibilty

c     end include file cchvar.inc

