
c     begin include file cdiss12.inc

c     + + + COMMON BLOCK DESCRIPTION + + +
c     + + + INSERT DESCRIPTION HERE  + + +

      common /diss12/   intsty(3000),timem(3000)

c     + + + VARIABLE DECLARATIONS + + +

      real              intsty,timem

c     + + + VARIABLE DEFINITIONS + + +

c     intsty(100) : rainfall intensity (m/s)
c     timem(100)  : elapsed time (s)
cAS   changed intsty and timem array from 200 to 3000

c     end include file cdiss12.inc

