<?php 
require '../config/settings.inc.php';
require '../autoload.php';

$year = isset($_REQUEST["year"]) ? intval($_REQUEST["year"]) : 2014;
$model_twp = isset($_REQUEST["model_twp"]) ? $_REQUEST["model_twp"] : "T90NR39W";
$huc12 = isset($_REQUEST["huc_12"]) ? $_REQUEST["huc_12"] : "102300050105";

$wepp_pgconn = pg_connect("dbname=wepp host=iemdb user=nobody");
$idep_pgconn = pg_connect("dbname=idep host=iemdb user=nobody");

$rs = pg_prepare($idep_pgconn, "SELECTOR", "SELECT to_char(valid, 'YYYYMMDD') as d, 
		avg_loss, avg_runoff, avg_precip from results_by_huc12
		WHERE huc_12 = $1 and valid BETWEEN $2 and $3");
$rs = pg_prepare($wepp_pgconn, "SELECTOR", "SELECT to_char(valid, 'YYYYMMDD') as d,
		avg_loss, avg_runoff, avg_precip from results_by_twp
		WHERE model_twp = $1 and valid BETWEEN $2 and $3");
$wepprs = pg_execute($wepp_pgconn, "SELECTOR", Array($model_twp, "$year-01-01", 
		"$year-12-31"));
$ideprs = pg_execute($idep_pgconn, "SELECTOR", Array($huc12, "$year-01-01",
		"$year-12-31"));

$events = Array();
for ($i=0; $row = @pg_fetch_array($wepprs, $i); $i++){
	$events[ $row["d"] ] = Array("wepp"=>$row);
}
for ($i=0; $row = @pg_fetch_array($ideprs, $i); $i++){
	if (! array_key_exists($row["d"], $events)){ 
		$events[$row["d"]] = Array(); 
	}
	$events[ $row["d"] ]["idep"] = $row;
}

function l($val){
	if ($val == null) return "";
	return sprintf("%.02f", $val * 4.463);
}

function p($val){
	if ($val == null) return "";
	return sprintf("%.02f", $val / 25.4);
}

$table = <<<EOF
<table border="1" cellspacing="2" cellpadding="0">
<tr><th rowspan="2">Date</th>
<th colspan="3">IDEP v1 (Township $model_twp)</th>
<th colspan="3">IDEP v2 (HUC 12 $huc12)</th>
</tr>
<tr><th>Precip [in]</th><th>Runoff [in]</th><th>Loss [tons/acre]</th>
<th>Precip [in]</th><th>Runoff [in]</th><th>Loss [tons/acre]</th></tr>
EOF;
$dates = array_keys($events);
asort($dates);
while (list($k,$v)=each($dates)){
	$table .= @sprintf("<tr><th>%s</th><td>%s</td><td>%s</td><td>%s</td>
			<td>%s</td><td>%s</td><td>%s</td></tr>", $v,
		p($events[$v]["wepp"]["avg_precip"]), p($events[$v]["wepp"]["avg_runoff"]),
		l($events[$v]["wepp"]["avg_loss"]),
		p($events[$v]["idep"]["avg_precip"]), p($events[$v]["idep"]["avg_runoff"]),
		l($events[$v]["idep"]["avg_loss"]));
}

$table .= "</table>";


$theme = new Sample\Theme('IDEP :: Daily Comparison IDEPv1 vs IDEPv2');
$theme->drawHeader();

echo <<<EOF
<form method="GET" name="uyear">
<input type="hidden" name="model_twp" value="{$model_twp}">
<input type="hidden" name="huc12" value="{$huc12}">
<p><strong>Enter Year:</strong> 
<input maxlength="4" size="8" type="text" name="year" value="{$year}">
<input type="submit" value="Change Year">
</form>

EOF;

echo $table; 

$theme->drawFooter(); 
?>
