<?php 
require '../config/settings.inc.php';
require '../autoload.php';

$year = isset($_REQUEST["year"]) ? intval($_REQUEST["year"]) : 2014;
$model_twp = isset($_REQUEST["model_twp"]) ? $_REQUEST["model_twp"] : "T90NR39W";
$huc12 = isset($_REQUEST["huc_12"]) ? $_REQUEST["huc_12"] : "102300050105";
$scenario = isset($_REQUEST["scenario"]) ? intval($_REQUEST["scenario"]): 0;

$wepp_pgconn = pg_connect("dbname=wepp host=iemdb user=nobody");
$idep_pgconn = pg_connect("dbname=idep host=iemdb user=nobody");

/* Yearly Totals */
$rs = pg_prepare($idep_pgconn, "YRSELECT", "SELECT 
		extract(year from valid) as d,
		sum(avg_loss) as sum_avg_loss, 
		sum(avg_runoff) as sum_avg_runoff, 
		sum(avg_delivery) as sum_avg_delivery from results_by_huc12
		WHERE huc_12 = $1 and scenario = 0 GROUP by d");
$rs = pg_prepare($wepp_pgconn, "YRSELECT", "SELECT 
		extract(year from valid) as d,
		sum(avg_loss) from results_by_twp
		WHERE model_twp = $1 and valid > '2007-01-01' GROUP by d");
$wepprs = pg_execute($wepp_pgconn, "YRSELECT", Array($model_twp));
$ideprs = pg_execute($idep_pgconn, "YRSELECT", Array($huc12));
$yrtotals = Array();
for ($i=0; $row = @pg_fetch_array($wepprs, $i); $i++){
	$yrtotals[ $row["d"] ] = Array("wepp"=>$row);
}
for ($i=0; $row = @pg_fetch_array($ideprs, $i); $i++){
	if (! array_key_exists($row["d"], $yrtotals)){
		$yrtotals[$row["d"]] = Array();
	}
	$yrtotals[ $row["d"] ]["idep"] = $row;
}


/* Daily Totals for the year */
$rs = pg_prepare($idep_pgconn, "SELECTOR", "SELECT to_char(valid, 'YYYYMMDD') as d, 
		avg_loss, avg_runoff, qc_precip from results_by_huc12
		WHERE huc_12 = $1 and valid BETWEEN $2 and $3 and scenario = 0");
$rs = pg_prepare($wepp_pgconn, "SELECTOR", "SELECT to_char(valid, 'YYYYMMDD') as d,
		avg_loss, avg_runoff, avg_precip from results_by_twp
		WHERE model_twp = $1 and valid BETWEEN $2 and $3");
$wepprs = pg_execute($wepp_pgconn, "SELECTOR", Array($model_twp, "$year-01-01", 
		"$year-12-31"));
$ideprs = pg_execute($idep_pgconn, "SELECTOR", Array($huc12, "$year-01-01",
		"$year-12-31"));

$events = Array();
for ($i=0; $row = @pg_fetch_array($wepprs, $i); $i++){
	$events[ $row["d"] ] = Array("wepp"=>$row);
}
for ($i=0; $row = @pg_fetch_array($ideprs, $i); $i++){
	if (! array_key_exists($row["d"], $events)){ 
		$events[$row["d"]] = Array(); 
	}
	$events[ $row["d"] ]["idep"] = $row;
}

function l($val){
	if ($val == null) return "";
	return sprintf("%.02f", $val * 4.463);
}

function p($val){
	if ($val == null) return "";
	return sprintf("%.02f", $val / 25.4);
}

$table2 = <<<EOF
<table class="wd-Table--striped wd-Table--hover wd-Table--bordered">
<thead><tr><th rowspan="2">Year</th>
<th>IDEP v1 (Township $model_twp)</th>
<th colspan="3">IDEP v2 (HUC 12 $huc12)</th>
</tr>
<tr>
 <th>Loss [tons/acre]</th>
 <th>Loss [tons/acre]</th>
 <th>Delivery [tons/acre]</th>
 <th>Runoff [inch]</th>
</tr>
</thead>
<tbody>
EOF;
$dates = array_keys($yrtotals);
asort($dates);
while (list($k,$v)=each($dates)){
	$table2 .= @sprintf("<tr><th><a href=\"compare.phtml?year=%s&model_twp=%s&huc_12=%s\">%s</a></th><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>", 
			$v, $model_twp, $huc12, $v,
			l($yrtotals[$v]["wepp"]["sum"]), 
			l($yrtotals[$v]["idep"]["sum_avg_loss"]),
			l($yrtotals[$v]["idep"]["sum_avg_delivery"]),
			p($yrtotals[$v]["idep"]["sum_avg_runoff"]));
}

$table2 .= "</tbody></table>";


$table = <<<EOF
<table class="wd-Table--striped wd-Table--hover wd-Table--bordered">
<thead><tr><th rowspan="2">Date</th>
<th colspan="3">IDEP v1 (Township $model_twp)</th>
<th colspan="3">IDEP v2 (HUC 12 $huc12)</th>
</tr>
<tr><th>Precip [in]</th><th>Runoff [in]</th><th>Loss [tons/acre]</th>
<th>Precip [in]</th><th>Runoff [in]</th><th>Loss [tons/acre]</th></tr></thead>
<tbody>
EOF;
$dates = array_keys($events);
asort($dates);
while (list($k,$v)=each($dates)){
	$table .= @sprintf("<tr><th>%s</th><td>%s</td><td>%s</td><td>%s</td>
			<td>%s</td><td>%s</td><td>%s</td></tr>", $v,
		p($events[$v]["wepp"]["avg_precip"]), p($events[$v]["wepp"]["avg_runoff"]),
		l($events[$v]["wepp"]["avg_loss"]),
		p($events[$v]["idep"]["qc_precip"]), p($events[$v]["idep"]["avg_runoff"]),
		l($events[$v]["idep"]["avg_loss"]));
}

$table .= "</tbody></table>";


$theme = new Sample\Theme('IDEP :: Comparison IDEPv1 vs IDEPv2');
$theme->drawHeader();


echo <<<EOF

<h3>Slope Comparison</h3>

<img src="/plots/slopes{$scenario}_{$huc12}_{$model_twp}.png" />

<h3>Yearly Totals</h3>
Click on the year to view daily output for that year.<br />
$table2

<h3>{$year} Daily Output</h3>
$table
EOF;

$theme->drawFooter(); 
?>
